In [2]:
import pandas as pd

---

#### **Referências ) - South German Credit**

- [Download do Dataset](google.com/url?q=https://archive.ics.uci.edu/dataset/522/south%2Bgerman%2Bcredit&sa=D&source=editors&ust=1789504988075720&usg=AOvVaw3xlcHinwJQ0wXAoDYT3PkP)

---

In [3]:
# D08 - South German Credit 
df_d08 = pd.read_csv("data/raw/german_credit.csv")
df_d08.head()

,status,duration,credit_history,purpose,amount,savings,employment_duration,installment_rate,personal_status_sex,other_debtors,...,property,age,other_installment_plans,housing,number_credits,job,people_liable,telephone,foreign_worker,credit_risk
0,no checking account,18,all credits at this bank paid back duly,car (used),1049,unknown/no savings account,< 1 yr,< 20,female : non-single or male : single,none,...,car or other,21,none,for free,1,skilled employee/official,0 to 2,no,no,good
1,no checking account,9,all credits at this bank paid back duly,others,2799,unknown/no savings account,1 <= ... < 4 yrs,25 <= ... < 35,male : married/widowed,none,...,unknown / no property,36,none,for free,3-Feb,skilled employee/official,3 or more,no,no,good
2,... < 0 DM,12,no credits taken/all credits paid back duly,retraining,841,... < 100 DM,4 <= ... < 7 yrs,25 <= ... < 35,female : non-single or male : single,none,...,unknown / no property,23,none,for free,1,unskilled - resident,0 to 2,no,no,good
3,no checking account,12,all credits at this bank paid back duly,others,2122,unknown/no savings account,1 <= ... < 4 yrs,20 <= ... < 25,male : married/widowed,none,...,unknown / no property,39,none,for free,3-Feb,unskilled - resident,3 or more,no,yes,good
4,no checking account,12,all credits at this bank paid back duly,others,2171,unknown/no savings account,1 <= ... < 4 yrs,< 20,male : married/widowed,none,...,car or other,38,bank,rent,3-Feb,unskilled - resident,0 to 2,no,yes,good

---

#### **01 ) - Verificação dos dados**

- 

---

In [4]:
float(df_d08.isna().sum().sum() / len(df_d08) * 100)

0.0

In [5]:
bool(df_d08.duplicated().any())

False

---

#### **02 ) - Tratamento dos dados**

- 

---

In [6]:
df_d08_clean = df_d08.copy()

#### 2.1 - *Tratamento para colunas específicas*

In [7]:

# Ajuste dos valores para a coluna number_credits
map_number_credits = {
    '1': '1',
    '3-Feb': '2-3',
    '5-Apr': '4-5',
    '>= 6': '>= 6'
}

df_d08_clean['credit_risk'] = df_d08['credit_risk'].map(map_number_credits)

In [8]:

# Ajuste dos valores para a coluna credit_risk
map_credit_risk = {
    'bad' : 0,
    'good' : 1
}

df_d08_clean['credit_risk'] = df_d08['credit_risk'].map(map_credit_risk)

#### 2.2 - *Dropando colunas*

In [9]:
# O dataset D08 não possui colunas que precisam ser dropadas

#### 2.3 - *Renomeando colunas*

In [10]:


# Renomeando a coluna alvo para TARGET
df_d08_clean = df_d08_clean.rename(columns={"credit_risk":'TARGET'})
# Aplicando a contagem padrão nas colunas
df_d08_clean.columns = [f"{idx}_{col}" for idx, col in enumerate(df_d08_clean.columns, start=1)]

#### 2.4 - *Tratamento para valores ausentes*

In [11]:
# O dataset D08 não possui valores ausentes

#### 2.5 - *Tratamento para valores duplicados*

In [12]:
# O dataset D08 não possui valores duplicados

#### 2.6 - *Salvando o resultado*

In [13]:
df_d08_clean.to_csv("data/input/D08_Clean.csv", index=False)
df_d08_clean.head()

,1_status,2_duration,3_credit_history,4_purpose,5_amount,6_savings,7_employment_duration,8_installment_rate,9_personal_status_sex,10_other_debtors,...,12_property,13_age,14_other_installment_plans,15_housing,16_number_credits,17_job,18_people_liable,19_telephone,20_foreign_worker,21_TARGET
0,no checking account,18,all credits at this bank paid back duly,car (used),1049,unknown/no savings account,< 1 yr,< 20,female : non-single or male : single,none,...,car or other,21,none,for free,1,skilled employee/official,0 to 2,no,no,1
1,no checking account,9,all credits at this bank paid back duly,others,2799,unknown/no savings account,1 <= ... < 4 yrs,25 <= ... < 35,male : married/widowed,none,...,unknown / no property,36,none,for free,3-Feb,skilled employee/official,3 or more,no,no,1
2,... < 0 DM,12,no credits taken/all credits paid back duly,retraining,841,... < 100 DM,4 <= ... < 7 yrs,25 <= ... < 35,female : non-single or male : single,none,...,unknown / no property,23,none,for free,1,unskilled - resident,0 to 2,no,no,1
3,no checking account,12,all credits at this bank paid back duly,others,2122,unknown/no savings account,1 <= ... < 4 yrs,20 <= ... < 25,male : married/widowed,none,...,unknown / no property,39,none,for free,3-Feb,unskilled - resident,3 or more,no,yes,1
4,no checking account,12,all credits at this bank paid back duly,others,2171,unknown/no savings account,1 <= ... < 4 yrs,< 20,male : married/widowed,none,...,car or other,38,bank,rent,3-Feb,unskilled - resident,0 to 2,no,yes,1

---

#### **03 ) - Status CSV**

- 

---

In [14]:
df_d08_status = pd.read_csv("data/input/D08_Status.csv")
df_d08_status['column'] = df_d08_clean.columns.tolist()
df_d08_status.to_csv("data/input/D08_Status.csv", index=False)
df_d08_status

,column,variable_type,variable_subtype,description,classification,transformation,status
0,1_status,qualitative,ordinal,NaN,NaN,NaN,NaN
1,2_duration,quantitative,continuous,NaN,NaN,NaN,NaN
2,3_credit_history,qualitative,ordinal,NaN,NaN,NaN,NaN
3,4_purpose,qualitative,nominal,NaN,NaN,NaN,NaN
4,5_amount,quantitative,continuous,NaN,NaN,NaN,NaN
5,6_savings,qualitative,ordinal,NaN,NaN,NaN,NaN
6,7_employment_duration,qualitative,ordinal,NaN,NaN,NaN,NaN
7,8_installment_rate,qualitative,ordinal,NaN,NaN,NaN,NaN
8,9_personal_status_sex,qualitative,nominal,NaN,NaN,NaN,NaN
9,10_other_debtors,qualitative,nominal,NaN,NaN,NaN,NaN
10,11_present_residence,qualitative,ordinal,NaN,NaN,NaN,NaN
11,12_property,qualitative,ordinal,NaN,NaN,NaN,NaN
12,13_age,quantitative,continuous,NaN,NaN,NaN,NaN
13,14_other_installment_plans,qualitative,nominal,NaN,NaN,NaN,NaN
14,15_housing,qualitative,nominal,NaN,NaN,NaN,NaN
15,16_number_credits,qualitative,ordinal,NaN,NaN,NaN,NaN
16,17_job,qualitative,ordinal,NaN,NaN,NaN,NaN
17,18_people_liable,qualitative,ordinal,NaN,NaN,NaN,NaN
18,19_telephone,qualitative,nominal,NaN,NaN,NaN,NaN
19,20_foreign_worker,qualitative,nominal,NaN,NaN,NaN,NaN
20,21_TARGET,qualitative,nominal,NaN,NaN,NaN,NaN